spring:
  cache:
    type: caffeine

caffeine:
  spec: maximumSize=500,expireAfterWrite=10m


sample-data:
  cities:
    - name: New York
      code: NYC
    - name: Los Angeles
      code: LAX
    - name: Chicago
      code: CHG
    - name: Miami
      code: MIA
  flights:
    - origin: NYC
      destination: LAX
      departure: 2026-02-10T09:00
      arrival: 2026-02-10T19:00
      price: 350.00
    - origin: NYC
      destination: CHG
      departure: 2026-02-11T09:30
      arrival: 2026-02-11T14:00
      price: 250.00
    - origin: NYC
      destination: MIA
      departure: 2026-02-12T10:20
      arrival: 2026-02-12T16:40
      price: 280.00
    - origin: CHG
      destination: NYC
      departure: 2026-02-11T09:30
      arrival: 2026-02-11T14:00
      price: 220.00
    - origin: CHG
      destination: LAX
      departure: 2026-03-10T09:00
      arrival: 2026-03-10T15:00
      price: 220.00
    - origin: LAX
      destination: NYC
      departure: 2026-02-15T14:00
      arrival: 2026-02-15T22:00
      price: 360.00
    - origin: LAX
      destination: CHG
      departure: 2026-02-12T12:00
      arrival: 2026-02-12T18:00
      price: 220.00
  hotels:
    - name: Grand New York Hotel
      city: NYC
      pricePerNight: 200.00
    - name: Sunset LA Resort
      city: LAX
      pricePerNight: 180.00
    - name: Chicago Willis Tower
      city: CHG
      pricePerNight: 160.00
    - name: Miami Ocean Drive Hotel
      city: MIA
      pricePerNight: 250.00
